openapi: 3.0.0
tags:
  - name: "platform-eng"
    description: Platform Engineering manages these endpoints.
info:
  title: mail-service
  version: '0.0.1'
  description: API for forwarding contact inquiries to Parcely
  contact:
    name: Engineering Team
    email: hello@parcely.us
servers:
  - url: 'http://localhost:3000'
paths:
  /mailService-fwdMessage:
    post:
      tags:
        - platform-eng
      summary: send-contact-inquiry
      operationId: post-mailService-fwdMessage
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      properties: {}
                required:
                  - errors
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                description: ''
                type: object
      requestBody:
        content:
          application/json:
            schema:
              description: ''
              type: object
              properties:
                email:
                  type: string
                  minLength: 1
                name:
                  type: string
                  minLength: 1
                body:
                  type: string
                  minLength: 1
              required:
                - email
                - name
                - body
        description: User info from website contact form
      description: Sends a message from the Parcely website contact form to the main inbox.
components:
  schemas: {}
