version: "3.1"

services:
  parcely_core:
    container_name: parcely_core.api
    image: parcely_core:0.0.1
    command: npm run start:app
    environment:
      - JWT_SECRET=superSecret
      - COMMIT_HASH=13626a216c8a4b38079d91a3750fa6c435adb0dd
      - GCLOUD_PROJECT=fakeProjectId
      - FIREBASE_CONFIG="{\"projectId\":\"fakeProjectId\",\"storageBucket\":\"fakeProjectId.appspot.com\"}"
      - NODE_ENV=local
    ports:
      - "3000:3000"
    volumes:
      - ./:/src
    networks:
      - shared_network
    depends_on: 
      - parcely_hw
  parcely_hw:
    container_name: parcely_hw.api
    image: parcely_hw:0.0.1
    environment:
      - COMMIT_HASH=13626a216c8a4b38079d91a3750fa6c435adb0dd
      - GCLOUD_PROJECT=fakeProjectId
      - FIREBASE_CONFIG="{\"projectId\":\"fakeProjectId\",\"storageBucket\":\"fakeProjectId.appspot.com\"}"
      - NODE_ENV=local
    ports:
      - "3001:3001"
    networks:
        - shared_network
networks:
    shared_network: