version: "3.1"

services:
  parcely:
    build: .
    container_name: api
    command: npm test
    environment:
      - JWT_SECRET=superSecret
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=mock_access_key
      - AWS_SECRET_ACCESS_KEY=mock_secret_key
      - COMMIT_HASH=13626a216c8a4b38079d91a3750fa6c435adb0dd
    volumes:
      - ./:/src
    networks:
      - shared_network
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    environment:
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sqs
    ports:
      - "4566:4566"
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
        - shared_network
networks:
    shared_network: