module.exports = {
  routes: {
    a: {
      originAddress: {
        street: '900 S Fremont Ave',
        city: 'Alhambra',
        state: 'CA',
        zip: '91803',
      },
      destinationAddress: {
        street: 'City Hall Park',
        city: 'New York',
        state: 'NY',
        zip: '10007',
      },
      trackingNumber: '3E1ADB42-B335-4DB6-96A2-962F9E614A80',
      waypoints: [
        {
          routeId: 'a',
          city: 'Los Angeles',
          state: 'CA',
          lat: '34°03′N',
          lng: '118°15′W',
        },
        {
          routeId: 'a',
          city: 'Barstow',
          state: 'CA',
          lat: '34°54′N',
          lng: '117°1′W',
        },
        {
          routeId: 'a',
          city: 'Las Vegas',
          state: 'NV',
          lat: '36°10′30″N',
          lng: '115°08′11″W',
        },
        {
          routeId: 'a',
          city: 'Fillmore',
          state: 'UT',
          lat: '38.967778°N',
          lng: '112.33083°W',
        },
        {
          routeId: 'a',
          city: 'Provo',
          state: 'UT',
          lat: '40°14′40″N',
          lng: '111°39′39″W',
        },
        {
          routeId: 'a',
          city: 'Grand Junction',
          state: 'CO',
          lat: '39°04′N',
          lng: '108°34′W',
        },
        {
          routeId: 'a',
          city: 'Denver',
          state: 'Co',
          lat: '39°44′21″N',
          lng: '104°59′25″W',
        },
        {
          routeId: 'a',
          city: 'Grand Island',
          state: 'NE',
          lat: '40°55′20″N',
          lng: '98°21′29″W',
        },
        {
          routeId: 'a',
          city: 'Lincoln',
          state: 'NE',
          lat: '40°48′32″N',
          lng: '96°40′44″W',
        },
        {
          routeId: 'a',
          city: 'Des Moines',
          state: 'IA',
          lat: '41°35′27″N',
          lng: '93°37′15″W',
        },
        {
          routeId: 'a',
          city: 'Cedar Rapids',
          state: 'IA',
          lat: '41°58′59″N',
          lng: '91°40′7″W',
        },
        {
          routeId: 'a',
          city: 'Rockford',
          state: 'IL',
          lat: '42°15′34″N',
          lng: '89°03′52″W',
        },
        {
          routeId: 'a',
          city: 'Chicago',
          state: 'IL',
          lat: '41.8781°N',
          lng: '87.6298°W',
        },
        {
          routeId: 'a',
          city: 'South Bend',
          state: 'IN',
          lat: '41°40′35″N',
          lng: '86°15′01″W',
        },
        {
          routeId: 'a',
          city: 'Toledo',
          state: 'OH',
          lat: '41°39′56″N',
          lng: '83°34′31″W',
        },
        {
          routeId: 'a',
          city: 'Youngstown',
          state: 'OH',
          lat: '41°6′N',
          lng: '80°39′W',
        },
        {
          routeId: 'a',
          city: 'Pittsburgh',
          state: 'PA',
          lat: '40°26′23″N',
          lng: '79°58′35″W',
        },
        {
          routeId: 'a',
          city: 'Mechanicsburg',
          state: 'PA',
          lat: '40°12′44″N',
          lng: '77°00′22″W',
        },
        {
          routeId: 'a',
          city: 'Harrisburg',
          state: 'PA',
          lat: '40°16′11″N',
          lng: '76°52′32″W',
        },
        {
          routeId: 'a',
          city: 'Hamburg',
          state: 'PA',
          lat: '40°33′N',
          lng: '75°59′W',
        },
        {
          routeId: 'a',
          city: 'Allentown',
          state: 'PA',
          lat: '40°36′06″N',
          lng: '75°28′38″W',
        },
        {
          routeId: 'a',
          city: 'Bethlehem',
          state: 'PA',
          lat: '40°37′34″N',
          lng: '75°22′32″W',
        },
        {
          routeId: 'a',
          city: 'Newark',
          state: 'NJ',
          lat: '40.72422°N',
          lng: '74.172574°W',
        },
        {
          routeId: 'a',
          city: 'New York',
          state: 'NY',
          lat: '40.712740°N',
          lng: '74.005974°W',
        },
      ],
    },
    b: {
      originAddress: {
        street: '1325 6th Ave',
        city: 'Seattle',
        state: 'WA',
        zip: '98101',
      },
      destinationAddress: {
        street: '844 NW 2nd St',
        city: 'Miami',
        state: 'FL',
        zip: '33128',
      },
      trackingNumber: '69064139-F30E-4C28-A190-6273650FEE50',
      waypoints: [
        {
          routeId: 'b',
          city: 'Seattle',
          state: 'WA',
          lat: '47°36′35″N',
          lng: '122°19′59″W',
        },
        {
          routeId: 'b',
          city: 'Ellensburg',
          state: 'WA',
          lat: '46.995°N',
          lng: '120.549°W',
        },
        {
          routeId: 'b',
          city: 'Spokane',
          state: 'WA',
          lat: '47°39′32″N',
          lng: '117°25′30″W',
        },
        {
          routeId: 'b',
          city: 'Missoula',
          state: 'MT',
          lat: '46°51′45″N',
          lng: '114°0′42″W',
        },
        {
          routeId: 'b',
          city: 'Butte',
          state: 'MT',
          lat: '45°59′56″N',
          lng: '112°31′27″W',
        },
        {
          routeId: 'b',
          city: 'Billings',
          state: 'MT',
          lat: '45°47′01″N',
          lng: '108°30′22″W',
        },
        {
          routeId: 'b',
          city: 'Rapid City',
          state: 'SD',
          lat: '44.076°N',
          lng: '103.228°W',
        },
        {
          routeId: 'b',
          city: 'Alexandria',
          state: 'SD',
          lat: '43°39′17″N',
          lng: '97°46′53″W',
        },
        {
          routeId: 'b',
          city: 'Sioux Falls',
          state: 'SD',
          lat: '43°32′11″N',
          lng: '96°43′54″W',
        },
        {
          routeId: 'b',
          city: 'Sioux City',
          state: 'IA',
          lat: '42°29′53″N',
          lng: '96°23′44″W',
        },
        {
          routeId: 'b',
          city: 'Omaha',
          state: 'NE',
          lat: '41°15′N',
          lng: '96°0′W',
        },
        {
          routeId: 'b',
          city: 'St Joseph',
          state: 'MO',
          lat: '39°45′29″N',
          lng: '94°50′12″W',
        },
        {
          routeId: 'b',
          city: 'Jefferson City',
          state: 'MO',
          lat: '38°34′36″N',
          lng: '92°10′25″W',
        },
        {
          routeId: 'b',
          city: 'Kansas City',
          state: 'MO',
          lat: '39°05′59″N',
          lng: '94°34′42″W',
        },
        {
          routeId: 'b',
          city: 'St. Louis',
          state: 'MO',
          lat: '38°37′38″N',
          lng: '90°11′52″W',
        },
        {
          routeId: 'b',
          city: 'Clarksdale',
          state: 'MS',
          lat: '34°12′N',
          lng: '90°34′W',
        },
        {
          routeId: 'b',
          city: 'Nashville',
          state: 'TN',
          lat: '36°09′44″N',
          lng: '86°46′28″W',
        },
        {
          routeId: 'b',
          city: 'Chattanooga',
          state: 'TN',
          lat: '35°2′44″N',
          lng: '85°16′2″W',
        },
        {
          routeId: 'b',
          city: 'Atlanta',
          state: 'GA',
          lat: '33°45′18″N',
          lng: '84°23′24″W',
        },
        {
          routeId: 'b',
          city: 'Macon',
          state: 'GA',
          lat: '32°50′5″N',
          lng: '83°39′6″W',
        },
        {
          routeId: 'b',
          city: 'Valdosta',
          state: 'GA',
          lat: '30°50′48″N',
          lng: '83°16′59″W',
        },
        {
          routeId: 'b',
          city: 'Gainesville',
          state: 'FL',
          lat: '29°39′7.19″N',
          lng: '82°19′29.97″W',
        },
        {
          routeId: 'b',
          city: 'Orlando',
          state: 'FL',
          lat: '28°32′24″N',
          lng: '81°22′48″W',
        },
        {
          routeId: 'b',
          city: 'Tampa',
          state: 'FL',
          lat: '27°58′05″N',
          lng: '82°28′35″W',
        },
        {
          routeId: 'b',
          city: 'Miami',
          state: 'FL',
          lat: '25.775163°N',
          lng: '80.208615°W',
        },

      ],
    },
    c: {
      originAddress: {
        street: '24 Beacon Street',
        city: 'Boston',
        state: 'MA',
        zip: '02108',
      },
      destinationAddress: {
        street: '969 Broadway Circle',
        city: 'San Diego',
        state: 'CA',
        zip: '92101',
      },
      trackingNumber: '11DD7AF1-06F2-4788-A236-B7DB4C99F407',
      waypoints: [
        {
          routeId: 'c',
          city: 'Boston',
          state: 'MA',
          lat: '42°21′29″N',
          lng: '-71°03′49″W',
        },
        {
          routeId: 'c',
          city: 'Worcester',
          state: 'MA',
          lat: '42°16′17″N',
          lng: '71°47′56″W',
        },
        {
          routeId: 'c',
          city: 'Hartford',
          state: 'CT',
          lat: '41°45′45″N',
          lng: '72°40′27″W',
        },
        {
          routeId: 'c',
          city: 'Danbury',
          state: 'CT',
          lat: '41°24′08″N',
          lng: '73°28′16″W',
        },
        {
          routeId: 'c',
          city: 'Scranton',
          state: 'PA',
          lat: '41°24′38″N',
          lng: '75°40′03″W',
        },
        {
          routeId: 'c',
          city: 'Bellefonte',
          state: 'PA',
          lat: '40°54′53″N',
          lng: '77°46′29″W',
        },
        {
          routeId: 'c',
          city: 'Pittsburgh',
          state: 'PA',
          lat: '40°26′23″N',
          lng: '79°58′35″W',
        },
        {
          routeId: 'c',
          city: 'Youngstown',
          state: 'OH',
          lat: '41°6′N',
          lng: '80°39′W',
        },
        {
          routeId: 'c',
          city: 'Akron',
          state: 'OH',
          lat: '41°4′23″N',
          lng: '81°31′4″W',
        },
        {
          routeId: 'c',
          city: 'Mansfield',
          state: 'OH',
          lat: '40°45′N',
          lng: '82°31′W',
        },
        {
          routeId: 'c',
          city: 'Columbus',
          state: 'OH',
          lat: '39°57′44″N',
          lng: '83°00′02″W',
        },
        {
          routeId: 'c',
          city: 'Dayton',
          state: 'OH',
          lat: '39°45′34″N',
          lng: '84°11′30″W',
        },
        {
          routeId: 'c',
          city: 'Indianapolis',
          state: 'IN',
          lat: '39°46′07″N',
          lng: '86°09′29″W',
        },
        {
          routeId: 'c',
          city: 'Decatur',
          state: 'IL',
          lat: '39°50′29.12″N',
          lng: '88°57′21.17″W',
        },
        {
          routeId: 'c',
          city: 'St. Louis',
          state: 'IL',
          lat: '38°37′38″N',
          lng: '90°11′52″W',
        },
        {
          routeId: 'c',
          city: 'Cuba',
          state: 'MO',
          lat: '38°3′47″N',
          lng: '91°24′12″W',
        },
        {
          routeId: 'c',
          city: 'Springfield',
          state: 'MO',
          lat: '37°12′55″N',
          lng: '93°17′54″W',
        },
        {
          routeId: 'c',
          city: 'Tulsa',
          state: 'OK',
          lat: '36°07′53″N',
          lng: '95°56′14″W',
        },
        {
          routeId: 'c',
          city: 'Oklahoma City',
          state: 'OK',
          lat: '35°28′7″N',
          lng: '97°31′17″W',
        },
        {
          routeId: 'c',
          city: 'Cheyenne',
          state: 'OK',
          lat: '35°36′50″N',
          lng: '99°40′17″W',
        },
        {
          routeId: 'c',
          city: 'Amarillo',
          state: 'TX',
          lat: '35°11′57″N',
          lng: '101°50′43″W',
        },
        {
          routeId: 'c',
          city: 'Santa Rosa',
          state: 'NM',
          lat: '34°56′32″N',
          lng: '104°41′2″W',
        },
        {
          routeId: 'c',
          city: 'Albuquerque',
          state: 'NM',
          lat: '35°06′39″N',
          lng: '106°36′36″W',
        },
        {
          routeId: 'c',
          city: 'Holbrook',
          state: 'AZ',
          lat: '34°54′26″N',
          lng: '110°9′46″W',
        },
        {
          routeId: 'c',
          city: 'Phoenix',
          state: 'AZ',
          lat: '33°27′N',
          lng: '112°04′W',
        },
        {
          routeId: 'c',
          city: 'Yuma',
          state: 'AZ',
          lat: '32°41′32″N',
          lng: '114°36′55″W',
        },
        {
          routeId: 'c',
          city: 'San Diego',
          state: 'CA',
          lat: '32°42′54″N',
          lng: '117°09′45″W',
        },
      ],
    },
    d: {
      originAddress: {
        street: '1113, Buckingham Drive',
        city: 'Tallahassee',
        state: 'FL',
        zip: '32308',
      },
      destinationAddress: {
        street: '405, E 8th Ave',
        city: 'Eugene',
        state: 'OR',
        zip: '97401',
      },
      trackingNumber: 'D746BFCA-7DF7-407A-BAC9-1EE3A33AF48C',
      waypoints: [
        {
          routeId: 'd',
          city: 'Tallahassee',
          state: 'FL',
          lat: '30°27′18″N',
          lng: '84°15′12″W',
        },
        {
          routeId: 'd',
          city: 'Troy',
          state: 'AL',
          lat: '31°48′32″N',
          lng: '85°58′12″W',
        },
        {
          routeId: 'd',
          city: 'Montogomery',
          state: 'AL',
          lat: '32°21′42″N',
          lng: '86°16′45″W',
        },
        {
          routeId: 'd',
          city: 'Birmingham',
          state: 'AL',
          lat: '52°28′48″N',
          lng: '01°54′09″W',
        },
        {
          routeId: 'd',
          city: 'Tupelo',
          state: 'MS',
          lat: '34°15′35″N',
          lng: '88°43′33″W',
        },
        {
          routeId: 'd',
          city: 'New Albany',
          state: 'MS',
          lat: '34°29′32″N',
          lng: '89°0′34″W',
        },
        {
          routeId: 'd',
          city: 'Memphis',
          state: 'TN',
          lat: '35°07′03″N',
          lng: '89°58′16″W',
        },
        {
          routeId: 'd',
          city: 'Jonesboro',
          state: 'AR',
          lat: '35°49′41″N',
          lng: '90°41′39″W',
        },
        {
          routeId: 'd',
          city: 'Kansas City',
          state: 'MO',
          lat: '39°05′59″N',
          lng: '94°34′42″W',
        },
        {
          routeId: 'd',
          city: 'Lincoln',
          state: 'NE',
          lat: '40°48′32″N',
          lng: '96°40′44″W',
        },
        {
          routeId: 'd',
          city: 'Kearney',
          state: 'NE',
          lat: '40°42′3″N',
          lng: '99°4′52″W',
        },
        {
          routeId: 'd',
          city: 'Kimball',
          state: 'NE',
          lat: '41°14′1″N',
          lng: '103°39′34″W',
        },
        {
          routeId: 'd',
          city: 'Ogallala',
          state: 'NE',
          lat: '41°7′44″N',
          lng: '101°43′10″W',
        },
        {
          routeId: 'd',
          city: 'Cheyenne',
          state: 'WY',
          lat: '41°8′24″N',
          lng: '104°49′13″W',
        },
        {
          routeId: 'd',
          city: 'Saratoga',
          state: 'WY',
          lat: '41°27′16″N',
          lng: '106°48′30″W',
        },
        {
          routeId: 'd',
          city: 'Evanston',
          state: 'WY',
          lat: '41°15′48″N',
          lng: '110°57′53″W',
        },
        {
          routeId: 'd',
          city: 'Logan',
          state: 'UT',
          lat: '41°44′16″N',
          lng: '111°49′51″W',
        },
        {
          routeId: 'd',
          city: 'Twin Falls',
          state: 'ID',
          lat: '42°33′20″N',
          lng: '114°28′15″W',
        },
        {
          routeId: 'd',
          city: 'Boise',
          state: 'ID',
          lat: '43°36′57″N',
          lng: '116°12′6″W',
        },
        {
          routeId: 'd',
          city: 'Ontario',
          state: 'OR',
          lat: '44°1′37″N',
          lng: '116°58′7″W',
        },
        {
          routeId: 'd',
          city: 'Burns',
          state: 'OR',
          lat: '43°35′13″N',
          lng: '119°3′36″W',
        },
        {
          routeId: 'd',
          city: 'Bend',
          state: 'OR',
          lat: '44°3′N',
          lng: '121°18′W',
        },
        {
          routeId: 'd',
          city: 'Eugene',
          state: 'OR',
          lat: '44°03′07″N',
          lng: '123°05′12″W',
        },
      ],
    },
  },
};
