name: Parcely Core Pipeline

on: 
  push:
    branches:
      - issno-* 
      - tf-*

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: "[STEP] Checkout"
        uses: actions/checkout@v2

      - name: "[STEP] Setup pipeline environment variables"
        run: |
          echo "GIT_SHA_SHORT=$(echo "$(git rev-parse --short "$GITHUB_SHA")")" >> $GITHUB_ENV

      - name: "[STEP] Set Node.js version"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "[STEP] Install app dependencies"
        run: npm install
      
      - name: "[STEP] Lint codebase"
        run: npm run lint:fix

      - name: "[STEP] Run Unit/Integration Tests"
        run: npm test
        env:
          JWT_SECRET: superSecret
          GCLOUD_PROJECT: fakeProjectId
          FIREBASE_CONFIG: "{\"projectId\":\"fakeProjectId\",\"storageBucket\":\"fakeProjectId.appspot.com\"}"
      
      - name: "[STEP] Set deployment environment variables"
        uses: w9jds/firebase-action@master
        with:
          args: functions:config:set env.commit_hash=${{ env.GIT_SHA_SHORT }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: "[STEP] Deploy to Firebase"
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      
      #- name: "[STEP] Configure AWS Credentials"
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: us-east-1

      #- name: "[STEP] Login to Amazon ECR"
      #  uses: aws-actions/amazon-ecr-login@v1
      #  id: login-ecr
      
      #- name: "[STEP] Build Docker image/push to AWS ECR"
      #  env:
      #    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #    ECR_REPOSITORY: parcely/core
      #  run: |
      #    echo "ECR_REGISTRY=$ECR_REGISTRY" >> $ECR_REGISTRY
      #    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.GIT_SHA_SHORT }} .
      #    docker push $ECR_REGISTRY/$ECR_REPOSITORY:"${{ env.GIT_SHA_SHORT }}"