name: Parcely Core Pipeline

on: 
  push:
    branches:
      - issno-* 
      - tf-*

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: "[STEP] Checkout"
        uses: actions/checkout@v2

      - name: "[STEP] Setup pipeline environment variables"
        run: |
          echo "GIT_SHA_SHORT=$(echo "$(git rev-parse --short "$GITHUB_SHA")")" >> $GITHUB_ENV

      - name: "[STEP] Set Node.js version"
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: "[STEP] Install app dependencies"
        run: cd ./functions && npm install

      - name: "[STEP] Run Unit/Integration Tests"
        run: cd ./functions && npm test
        env:
          JWT_SECRET: superSecret
      
      #- name: "[STEP] Configure AWS Credentials"
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: us-east-1

      #- name: "[STEP] Login to Amazon ECR"
      #  uses: aws-actions/amazon-ecr-login@v1
      #  id: login-ecr
      
      #- name: "[STEP] Build Docker image/push to AWS ECR"
      #  env:
      #    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #    ECR_REPOSITORY: parcely/core
      #  run: |
      #    echo "ECR_REGISTRY=$ECR_REGISTRY" >> $ECR_REGISTRY
      #    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.GIT_SHA_SHORT }} .
      #    docker push $ECR_REGISTRY/$ECR_REPOSITORY:"${{ env.GIT_SHA_SHORT }}"