name: Parcely Core Pipeline

on: 
  push:
    branches:
      - issno-* 
      - master

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: "[STEP] Checkout"
        uses: actions/checkout@v2

      - name: "[STEP] Set Node.js version"
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: "[STEP] Install app dependencies"
        run: npm install
      
      - name: "[STEP] Lint codebase"
        run: npm run lint:fix

      - name: "[STEP] Run Unit/Integration Tests"
        run: npm test
        env:
          JWT_SECRET: superSecret

  deploy:
    name: deploy
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: "[STEP] Checkout"
        uses: actions/checkout@master

      - name: "[STEP] Setup pipeline environment variables"
        run: |
          echo "GIT_SHA_SHORT=$(echo "$(git rev-parse --short "$GITHUB_SHA")")" >> $GITHUB_ENV

      - name: "[STEP] Deploy to Heroku"
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: evening-bastion-52298
          heroku_email: sean.travis.taylor@gmail.com
          healthcheck: https://evening-bastion-52298.herokuapp.com/status
        env: 
          HD_COMMIT_HASH: ${{ env.GIT_SHA_SHORT }}    

      #- name: "[STEP] Configure AWS Credentials"
      #  uses: aws-actions/configure-aws-credentials@v1
      #  with:
      #    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    aws-region: us-east-1

      #- name: "[STEP] Login to Amazon ECR"
      #  uses: aws-actions/amazon-ecr-login@v1
      #  id: login-ecr
      
      #- name: "[STEP] Build Docker image/push to AWS ECR"
      #  env:
      #    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #    ECR_REPOSITORY: parcely/core
      #  run: |
      #    echo "ECR_REGISTRY=$ECR_REGISTRY" >> $ECR_REGISTRY
      #    docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.GIT_SHA_SHORT }} .
      #    docker push $ECR_REGISTRY/$ECR_REPOSITORY:"${{ env.GIT_SHA_SHORT }}"